/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MoppyMainWindow.java
 *
 * Created on Oct 8, 2011, 8:34:57 PM
 */
package moppydesk;

import moppydesk.arduino.MoppyComSequencer;
import gnu.io.CommPortIdentifier;
import java.awt.Component;
import java.io.File;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.*;
import moppydesk.raspberry.JFlopPiSequencer;

/**
 *
 * @author Sam
 */
public class MoppyMainWindow extends javax.swing.JFrame implements MoppyStatusConsumer {

    static String PREF_COM_PORT = "comPort";
    static String PREF_LOADED_SEQ = "loadedSequencePath";
    MoppyUI app;
    Preferences prefs = Preferences.userNodeForPackage(MoppyUI.class);
    final JFileChooser sequenceChooser = new JFileChooser();
    boolean comboBoxReady = false;

    /**
     * Creates new form MoppyMainWindow
     */
    public MoppyMainWindow(MoppyUI app) {
        this.app = app;
        initComponents();

        updateComSelectionMenu();

        statusLabel.setText("Ready");

//        initializeSequencer((String) comSelectionMenu.getSelectedItem());
//        
//        
    }

    private void updateComSelectionMenu() {
        comboBoxReady = false;
        comSelectionMenu.removeAllItems();
        Enumeration<CommPortIdentifier> e = CommPortIdentifier.getPortIdentifiers();
        while (e.hasMoreElements()) {
            comSelectionMenu.addItem(e.nextElement().getName());
        }
        comSelectionMenu.setSelectedItem(prefs.get(PREF_COM_PORT, ""));
        comboBoxReady = true;
    }

    private void initializeComSequencer(String comPort) {
        statusLabel.setText("Initializing sequencer...");
        if (app.ms != null) {
            app.ms.closeSequencer();
        }
        try {
            app.ms = new MoppyComSequencer(comPort);
            app.ms.addListener(this);
        } catch (Exception ex) {
            Logger.getLogger(MoppyMainWindow.class.getName()).log(Level.SEVERE, null, ex);
            statusLabel.setText("Sequencer initialization error!");
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        statusLabel.setText("Sequencer connected to " + comPort);

        String previouslyLoadedFile = prefs.get(PREF_LOADED_SEQ, null);
        if (previouslyLoadedFile != null) {
            loadSequenceFile(new File(previouslyLoadedFile));
        }

        setSequenceControlsEnabled(true);
        connectSeqButton.setText("Disconnect");
    }

    private void initializeUDPSequencer(String ip, int port) {
        statusLabel.setText("Initializing sequencer...");
        if (app.ms != null) {
            app.ms.closeSequencer();
        }
        try {
            app.ms = new JFlopPiSequencer(ip, port);
            app.ms.addListener(this);
        } catch (Exception ex) {
            Logger.getLogger(MoppyMainWindow.class.getName()).log(Level.SEVERE, null, ex);
            statusLabel.setText("Sequencer initialization error!");
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        statusLabel.setText("Sequencer connected to " + ip + " on port " + port);

        String previouslyLoadedFile = prefs.get(PREF_LOADED_SEQ, null);
        if (previouslyLoadedFile != null) {
            loadSequenceFile(new File(previouslyLoadedFile));
        }

        setSequenceControlsEnabled(true);
        connectUDPButton1.setText("Disconnect");
    }

    private void shutdownSequencer() {
        statusLabel.setText("Closing sequencer...");
        if (app.ms != null) {
            app.ms.closeSequencer();
            app.ms = null;
        }
        setSequenceControlsEnabled(false);
        connectSeqButton.setText("Connect");
        connectUDPButton1.setText("Connect");
        connectSeqButton.setEnabled(true);
        connectUDPButton1.setEnabled(true);
        statusLabel.setText("Sequencer closed");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        sequencerControlsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sequenceNameLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        bpmLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        comSelectionMenu = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        ipTextField = new javax.swing.JTextField();
        portTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        connectSeqButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        connectUDPButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MoppyDesk");
        setMinimumSize(new java.awt.Dimension(480, 410));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                MoppyMainWindow.this.windowClosing(evt);
            }
        });

        statusLabel.setText("Loading application...");
        statusLabel.setName("statusLabel"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jTabbedPane1.setName("bridgePanel"); // NOI18N

        jPanel1.setName("sequencerPanel"); // NOI18N
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                seqTabHidden(evt);
            }
        });

        sequencerControlsPanel.setName("sequencerControlsPanel"); // NOI18N
        sequencerControlsPanel.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel1.setText("Current Sequence:");
        jLabel1.setEnabled(false);
        jLabel1.setName("jLabel1"); // NOI18N

        sequenceNameLabel.setText("<None loaded>");
        sequenceNameLabel.setEnabled(false);
        sequenceNameLabel.setName("sequenceNameLabel"); // NOI18N

        startButton.setText("Start");
        startButton.setEnabled(false);
        startButton.setName("startButton"); // NOI18N
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonClicked(evt);
            }
        });

        stopButton.setText("Stop/Reset");
        stopButton.setEnabled(false);
        stopButton.setName("stopButton"); // NOI18N
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopResetClicked(evt);
            }
        });

        loadButton.setText("Load Sequence");
        loadButton.setEnabled(false);
        loadButton.setName("loadButton"); // NOI18N
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSequence(evt);
            }
        });

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMaximum(210);
        jSlider1.setMinimum(20);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(120);
        jSlider1.setEnabled(false);
        jSlider1.setName("jSlider1"); // NOI18N
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tempoSliderChanged(evt);
            }
        });

        bpmLabel.setText(jSlider1.getValue() + " bpm");
        bpmLabel.setEnabled(false);
        bpmLabel.setName("bpmLabel"); // NOI18N

        javax.swing.GroupLayout sequencerControlsPanelLayout = new javax.swing.GroupLayout(sequencerControlsPanel);
        sequencerControlsPanel.setLayout(sequencerControlsPanelLayout);
        sequencerControlsPanelLayout.setHorizontalGroup(
            sequencerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sequencerControlsPanelLayout.createSequentialGroup()
                .addGroup(sequencerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sequencerControlsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sequencerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sequencerControlsPanelLayout.createSequentialGroup()
                                .addGroup(sequencerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sequenceNameLabel)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                                .addComponent(loadButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sequencerControlsPanelLayout.createSequentialGroup()
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(startButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stopButton))))
                    .addGroup(sequencerControlsPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(bpmLabel)))
                .addContainerGap())
        );
        sequencerControlsPanelLayout.setVerticalGroup(
            sequencerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sequencerControlsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sequencerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sequencerControlsPanelLayout.createSequentialGroup()
                        .addGroup(sequencerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sequencerControlsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sequenceNameLabel))
                            .addComponent(loadButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(sequencerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(sequencerControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(stopButton)
                                .addComponent(startButton))
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sequencerControlsPanelLayout.createSequentialGroup()
                        .addComponent(bpmLabel)
                        .addGap(54, 54, 54))))
        );

        bpmLabel.getAccessibleContext().setAccessibleName(jSlider1.getValue() + " bpm");

        jSeparator2.setName("jSeparator2"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sequencerControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sequencerControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sequencer", jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N

        comSelectionMenu.setName("comSelectionMenu"); // NOI18N
        comSelectionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comPortSelected(evt);
            }
        });

        jLabel3.setText("Arduino Port:");
        jLabel3.setName("jLabel3"); // NOI18N

        ipTextField.setName("ipTextField");

        portTextField.setInputVerifier(new InputVerifier() {
            public boolean verify(JComponent comp) {
                boolean returnValue = true;
                JTextField textField = (JTextField)comp;
                String content = textField.getText();
                if (content.length() != 0) {
                    try {
                        Integer.parseInt(textField.getText());
                    } catch (NumberFormatException e) {
                        getToolkit().beep();
                        returnValue = false;
                    }
                }
                return returnValue;
            }
        });
        portTextField.setName("portTextField");
        portTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("IP");
        jLabel4.setName("jLabel4");

        jLabel5.setText("Port");
        jLabel5.setName("jLabel5");

        connectSeqButton.setText("Connect");
        connectSeqButton.setToolTipText("Attempts to open selected COM port.");
        connectSeqButton.setName("connectSequencerButton"); // NOI18N
        connectSeqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectSequencerPressed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setName("jSeparator3");

        jLabel2.setText("Use Arduino");
        jLabel2.setName("jLabel2");

        jLabel6.setText("Use Raspberry");
        jLabel6.setName("jLabel6");

        connectUDPButton1.setText("Connect");
        connectUDPButton1.setToolTipText("Attempts to open selected COM port.");
        connectUDPButton1.setName("connectUDPButton1");
        connectUDPButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectUDPButton1connectSequencerPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectSeqButton)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(comSelectionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(connectUDPButton1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comSelectionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(connectUDPButton1)))
                            .addComponent(connectSeqButton))
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bridge", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(statusLabel)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Bridge"); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopResetClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopResetClicked
        statusLabel.setText("Stopping...");
        app.ms.stopSequencer();
        startButton.setEnabled(true);
        statusLabel.setText("Stopped");
    }//GEN-LAST:event_stopResetClicked

    private void startButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonClicked
        startButton.setEnabled(false);
        app.ms.startSequencer();
    }//GEN-LAST:event_startButtonClicked

    private void loadSequence(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSequence
        String previouslyLoaded = prefs.get(PREF_LOADED_SEQ, null);
        if (previouslyLoaded != null) {
            sequenceChooser.setCurrentDirectory(new File(previouslyLoaded));
        }
        int returnVal = sequenceChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            loadSequenceFile(sequenceChooser.getSelectedFile());
        } else {
            //Cancelled
        }
    }//GEN-LAST:event_loadSequence

    private void loadSequenceFile(File sequenceFile) {
        try {
            statusLabel.setText("Loading file...");
            app.ms.loadFile(sequenceFile.getPath());
            sequenceNameLabel.setText(sequenceFile.getName());
            prefs.put(PREF_LOADED_SEQ, sequenceFile.getPath());
            statusLabel.setText("Loaded " + sequenceFile.getName());
            startButton.setEnabled(true);
        } catch (Exception ex) {
            Logger.getLogger(MoppyMainWindow.class.getName()).log(Level.SEVERE, null, ex);
            statusLabel.setText("File loading error!");
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    private void tempoSliderChanged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempoSliderChanged
        JSlider s = (JSlider) evt.getSource();
        app.ms.setTempo(s.getValue());
        bpmLabel.setText(s.getValue() + " bpm");
    }//GEN-LAST:event_tempoSliderChanged

    private void comPortSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comPortSelected
        JComboBox cb = (JComboBox) evt.getSource();
        if (comboBoxReady) {
            String comPort = (String) cb.getSelectedItem();
            shutdownSequencer();
            prefs.put(PREF_COM_PORT, comPort);
        }
    }//GEN-LAST:event_comPortSelected

    private void windowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosing
        if (app.ms != null) {
            app.ms.closeSequencer();
        }
    }//GEN-LAST:event_windowClosing

    private void connectSequencerPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectSequencerPressed
        if (connectSeqButton.getText().equals("Connect")) {
            initializeComSequencer((String) comSelectionMenu.getSelectedItem());
            connectUDPButton1.setEnabled(false);
        } else {
            shutdownSequencer();
            connectUDPButton1.setEnabled(true);
        }
    }//GEN-LAST:event_connectSequencerPressed

    private void seqTabHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_seqTabHidden
        shutdownSequencer();
    }//GEN-LAST:event_seqTabHidden

    private void portTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portTextFieldActionPerformed

    private void connectUDPButton1connectSequencerPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectUDPButton1connectSequencerPressed
        if (connectUDPButton1.getText().equals("Connect")) {
            initializeUDPSequencer((String) ipTextField.getText(),Integer.parseInt(portTextField.getText()));
            connectSeqButton.setEnabled(false);
        } else {
            shutdownSequencer();
            connectSeqButton.setEnabled(true);
        }
    }//GEN-LAST:event_connectUDPButton1connectSequencerPressed

    private void setSequenceControlsEnabled(boolean enabled) {
        for (Component c : sequencerControlsPanel.getComponents()) {
            c.setEnabled(enabled);
        }
    }

    public void tempoChanged(int newTempo) {
        jSlider1.setValue(newTempo);
        bpmLabel.setText(newTempo + " bpm");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bpmLabel;
    private javax.swing.JComboBox comSelectionMenu;
    private javax.swing.JButton connectSeqButton;
    private javax.swing.JButton connectUDPButton1;
    private javax.swing.JTextField ipTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField portTextField;
    private javax.swing.JLabel sequenceNameLabel;
    private javax.swing.JPanel sequencerControlsPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
